server:
  port: 7110

spring:
  application:
    name: webflux

management:
  tracing:
    sampling:
      probability: 1.0

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# For tests
logging.level.org.springframework.cloud.sleuth: DEBUG
